"""friend_and_friend_requests

Revision ID: 1c04376bc79a
Revises: d75aca615ae4
Create Date: 2025-05-13 12:49:32.304282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c04376bc79a'
down_revision = 'd75aca615ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('account_a', sa.Integer(), nullable=True),
    sa.Column('account_b', sa.Integer(), nullable=True),
    sa.Column('friends_since', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_a'], ['user.id'], ),
    sa.ForeignKeyConstraint(['account_b'], ['user.id'], )
    )
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_to', sa.Integer(), nullable=False),
    sa.Column('account_from', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_from'], ['user.id'], ),
    sa.ForeignKeyConstraint(['account_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_request')
    op.drop_table('friend')
    # ### end Alembic commands ###
