"""Update Movie model to match CSV structure

Revision ID: 25504ef05fc1
Revises: 3a6899b665ff
Create Date: 2025-05-10 16:18:57.327962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25504ef05fc1'
down_revision = '3a6899b665ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=False))
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=False))
        batch_op.drop_column('release_year')

    # ### end Alembic commands ###
