"""change friend stuff

Revision ID: a732896ff0c6
Revises: 1c04376bc79a
Create Date: 2025-05-14 12:05:24.899924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a732896ff0c6'
down_revision = '1c04376bc79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_friend')
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('friends_since')

    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.alter_column('account_to',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('account_from',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.alter_column('account_from',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('account_to',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friends_since', sa.DATE(), nullable=True))

    op.create_table('_alembic_tmp_friend',
    sa.Column('account_a', sa.INTEGER(), nullable=True),
    sa.Column('account_b', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['account_a'], ['user.id'], ),
    sa.ForeignKeyConstraint(['account_b'], ['user.id'], )
    )
    # ### end Alembic commands ###
