"""title and release year unique constraint

Revision ID: d75aca615ae4
Revises: 25504ef05fc1
Create Date: 2025-05-12 22:04:02.238888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75aca615ae4'
down_revision = '25504ef05fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('avg_rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_index('ix_movie_title')
        batch_op.create_index(batch_op.f('ix_movie_title'), ['title'], unique=False)
        batch_op.create_unique_constraint('unique movie title and year', ['title', 'release_year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint('unique movie title and year', type_='unique')
        batch_op.drop_index(batch_op.f('ix_movie_title'))
        batch_op.create_index('ix_movie_title', ['title'], unique=1)
        batch_op.alter_column('avg_rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
