# Generated by Django 3.1.7 on 2021-05-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='douban_id',
            field=models.CharField(max_length=128, null=True, verbose_name='豆瓣id'),
        ),
        migrations.AddField(
            model_name='movie',
            name='douban_link',
            field=models.URLField(default='', verbose_name='豆瓣初始链接'),
            preserve_default=False,
        ),
    ]
