# Generated by Django 3.1.7 on 2025-04-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20250425_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='movie_uploads/', verbose_name='CSV File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Processing Status')),
                ('processed_count', models.IntegerField(default=0, verbose_name='Processed Movies Count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Movie Upload',
                'verbose_name_plural': 'Movie Uploads',
            },
        ),
    ]
