# Generated by Django 3.1.7 on 2025-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_movieupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieupload',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
