# Generated by Django 3.1.7 on 2025-04-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_movieupload_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_key', models.CharField(max_length=64, unique=True, verbose_name='Share Key')),
                ('title', models.CharField(max_length=255, verbose_name='Share Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public Sharing')),
                ('movies', models.ManyToManyField(to='user.Movie', verbose_name='Shared Movies')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_to_me', to='user.User', verbose_name='Shared With Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shared Recommendation',
                'verbose_name_plural': 'Shared Recommendations',
            },
        ),
    ]
